### ISSUE TITLE
Filled in version of tutorial

### ISSUE THREAD

**Issue by mridulsar** [theadamsabra/Jupyter-Pandas-Numpy-Matplotlib-Pyplot-Basics#1]
I would love to see the post-filled in version to this script. Thanks!

**Comment by theadamsabra** [comment]
I intentionally put up the empty notebook for people to watch the video and fill it in and mess around with the function as they go along

**Comment by theadamsabra** [comment]
Actually, I'll upload one sometime later today. I think it's best to have both uploaded.
